// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public final class Izbori {
  private Izbori() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_VoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_VoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_VoteRequest_VotesPerCandidateEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_VoteRequest_VotesPerCandidateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_VoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_VoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_StatisticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_StatisticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_StatisticsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_StatisticsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_StatisticsResponse_ResultsPerCandidateEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_StatisticsResponse_ResultsPerCandidateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_LogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_LogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_LogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_LeaderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_LeaderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_izbori_LeaderInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_izbori_LeaderInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014izbori.proto\022\006izbori\"\347\001\n\013VoteRequest\022\025" +
      "\n\rcontroller_id\030\001 \001(\005\022\022\n\nstation_id\030\002 \001(" +
      "\005\022\023\n\013total_voted\030\003 \001(\005\022\025\n\rinvalid_votes\030" +
      "\004 \001(\005\022G\n\023votes_per_candidate\030\005 \003(\0132*.izb" +
      "ori.VoteRequest.VotesPerCandidateEntry\0328" +
      "\n\026VotesPerCandidateEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\005:\0028\001\"U\n\014VoteResponse\022\"\n\006stat" +
      "us\030\001 \001(\0162\022.izbori.VoteStatus\022\017\n\007message\030" +
      "\002 \001(\t\022\020\n\010verified\030\003 \001(\010\"\023\n\021StatisticsReq" +
      "uest\"\260\002\n\022StatisticsResponse\022\033\n\023percentag" +
      "e_reported\030\001 \001(\001\022\032\n\022turnout_percentage\030\002" +
      " \001(\001\022R\n\025results_per_candidate\030\003 \003(\01323.iz" +
      "bori.StatisticsResponse.ResultsPerCandid" +
      "ateEntry\022\036\n\026stations_needing_retry\030\004 \001(\005" +
      "\022\026\n\016total_stations\030\005 \001(\005\022\031\n\021verified_sta" +
      "tions\030\006 \001(\005\032:\n\030ResultsPerCandidateEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\":\n\010LogEn" +
      "try\022\026\n\016entry_at_index\030\001 \001(\003\022\026\n\016log_entry" +
      "_data\030\002 \001(\014\"b\n\013LogResponse\022!\n\006status\030\001 \001" +
      "(\0162\021.izbori.LogStatus\022\026\n\016entry_at_index\030" +
      "\002 \001(\003\022\030\n\020last_entry_index\030\003 \001(\003\"\017\n\rLeade" +
      "rRequest\"6\n\nLeaderInfo\022\021\n\tim_leader\030\001 \001(" +
      "\010\022\025\n\rhostname_port\030\002 \001(\t*\212\001\n\nVoteStatus\022" +
      "\006\n\002OK\020\000\022\017\n\013INVALID_SUM\020\001\022\016\n\nNOT_LEADER\020\002" +
      "\022\023\n\017STATION_BLOCKED\020\003\022\027\n\023VERIFICATION_FA" +
      "ILED\020\004\022\024\n\020STATION_VERIFIED\020\005\022\017\n\013NEEDS_RE" +
      "TRY\020\006*?\n\tLogStatus\022\n\n\006LOG_OK\020\000\022\030\n\024LOG_HA" +
      "SNT_LAST_ENTRY\020\001\022\014\n\010IO_ERROR\020\0022\223\001\n\017Elect" +
      "ionService\0228\n\013SubmitVotes\022\023.izbori.VoteR" +
      "equest\032\024.izbori.VoteResponse\022F\n\rGetStati" +
      "stics\022\031.izbori.StatisticsRequest\032\032.izbor" +
      "i.StatisticsResponse2\206\001\n\024ReplicatedLogSe" +
      "rvice\0222\n\tAppendLog\022\020.izbori.LogEntry\032\023.i" +
      "zbori.LogResponse\022:\n\rGetLeaderInfo\022\025.izb" +
      "ori.LeaderRequest\032\022.izbori.LeaderInfoB\032\n" +
      "\026rs.ac.fink.izbori.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_izbori_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_izbori_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_VoteRequest_descriptor,
        new java.lang.String[] { "ControllerId", "StationId", "TotalVoted", "InvalidVotes", "VotesPerCandidate", });
    internal_static_izbori_VoteRequest_VotesPerCandidateEntry_descriptor =
      internal_static_izbori_VoteRequest_descriptor.getNestedTypes().get(0);
    internal_static_izbori_VoteRequest_VotesPerCandidateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_VoteRequest_VotesPerCandidateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_izbori_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_izbori_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_VoteResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Verified", });
    internal_static_izbori_StatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_izbori_StatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_StatisticsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_izbori_StatisticsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_izbori_StatisticsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_StatisticsResponse_descriptor,
        new java.lang.String[] { "PercentageReported", "TurnoutPercentage", "ResultsPerCandidate", "StationsNeedingRetry", "TotalStations", "VerifiedStations", });
    internal_static_izbori_StatisticsResponse_ResultsPerCandidateEntry_descriptor =
      internal_static_izbori_StatisticsResponse_descriptor.getNestedTypes().get(0);
    internal_static_izbori_StatisticsResponse_ResultsPerCandidateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_StatisticsResponse_ResultsPerCandidateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_izbori_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_izbori_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_LogEntry_descriptor,
        new java.lang.String[] { "EntryAtIndex", "LogEntryData", });
    internal_static_izbori_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_izbori_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_LogResponse_descriptor,
        new java.lang.String[] { "Status", "EntryAtIndex", "LastEntryIndex", });
    internal_static_izbori_LeaderRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_izbori_LeaderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_LeaderRequest_descriptor,
        new java.lang.String[] { });
    internal_static_izbori_LeaderInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_izbori_LeaderInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_izbori_LeaderInfo_descriptor,
        new java.lang.String[] { "ImLeader", "HostnamePort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
