// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public interface LeaderInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:izbori.LeaderInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool im_leader = 1;</code>
   * @return The imLeader.
   */
  boolean getImLeader();

  /**
   * <code>string hostname_port = 2;</code>
   * @return The hostnamePort.
   */
  java.lang.String getHostnamePort();
  /**
   * <code>string hostname_port = 2;</code>
   * @return The bytes for hostnamePort.
   */
  com.google.protobuf.ByteString
      getHostnamePortBytes();
}
