// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public interface LeaderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:izbori.LeaderRequest)
    com.google.protobuf.MessageOrBuilder {
}
