// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public interface LogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:izbori.LogEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 entry_at_index = 1;</code>
   * @return The entryAtIndex.
   */
  long getEntryAtIndex();

  /**
   * <code>bytes log_entry_data = 2;</code>
   * @return The logEntryData.
   */
  com.google.protobuf.ByteString getLogEntryData();
}
