// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public interface LogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:izbori.LogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.izbori.LogStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.izbori.LogStatus status = 1;</code>
   * @return The status.
   */
  rs.ac.fink.izbori.grpc.LogStatus getStatus();

  /**
   * <code>int64 entry_at_index = 2;</code>
   * @return The entryAtIndex.
   */
  long getEntryAtIndex();

  /**
   * <code>int64 last_entry_index = 3;</code>
   * @return The lastEntryIndex.
   */
  long getLastEntryIndex();
}
