// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

/**
 * Protobuf type {@code izbori.LogResponse}
 */
public final class LogResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:izbori.LogResponse)
    LogResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogResponse.newBuilder() to construct.
  private LogResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogResponse() {
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LogResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_LogResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_LogResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.ac.fink.izbori.grpc.LogResponse.class, rs.ac.fink.izbori.grpc.LogResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <code>.izbori.LogStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.izbori.LogStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public rs.ac.fink.izbori.grpc.LogStatus getStatus() {
    rs.ac.fink.izbori.grpc.LogStatus result = rs.ac.fink.izbori.grpc.LogStatus.forNumber(status_);
    return result == null ? rs.ac.fink.izbori.grpc.LogStatus.UNRECOGNIZED : result;
  }

  public static final int ENTRY_AT_INDEX_FIELD_NUMBER = 2;
  private long entryAtIndex_ = 0L;
  /**
   * <code>int64 entry_at_index = 2;</code>
   * @return The entryAtIndex.
   */
  @java.lang.Override
  public long getEntryAtIndex() {
    return entryAtIndex_;
  }

  public static final int LAST_ENTRY_INDEX_FIELD_NUMBER = 3;
  private long lastEntryIndex_ = 0L;
  /**
   * <code>int64 last_entry_index = 3;</code>
   * @return The lastEntryIndex.
   */
  @java.lang.Override
  public long getLastEntryIndex() {
    return lastEntryIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != rs.ac.fink.izbori.grpc.LogStatus.LOG_OK.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (entryAtIndex_ != 0L) {
      output.writeInt64(2, entryAtIndex_);
    }
    if (lastEntryIndex_ != 0L) {
      output.writeInt64(3, lastEntryIndex_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != rs.ac.fink.izbori.grpc.LogStatus.LOG_OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (entryAtIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, entryAtIndex_);
    }
    if (lastEntryIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, lastEntryIndex_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.ac.fink.izbori.grpc.LogResponse)) {
      return super.equals(obj);
    }
    rs.ac.fink.izbori.grpc.LogResponse other = (rs.ac.fink.izbori.grpc.LogResponse) obj;

    if (status_ != other.status_) return false;
    if (getEntryAtIndex()
        != other.getEntryAtIndex()) return false;
    if (getLastEntryIndex()
        != other.getLastEntryIndex()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + ENTRY_AT_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntryAtIndex());
    hash = (37 * hash) + LAST_ENTRY_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastEntryIndex());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.LogResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.ac.fink.izbori.grpc.LogResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code izbori.LogResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:izbori.LogResponse)
      rs.ac.fink.izbori.grpc.LogResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_LogResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_LogResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.ac.fink.izbori.grpc.LogResponse.class, rs.ac.fink.izbori.grpc.LogResponse.Builder.class);
    }

    // Construct using rs.ac.fink.izbori.grpc.LogResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      entryAtIndex_ = 0L;
      lastEntryIndex_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_LogResponse_descriptor;
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.LogResponse getDefaultInstanceForType() {
      return rs.ac.fink.izbori.grpc.LogResponse.getDefaultInstance();
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.LogResponse build() {
      rs.ac.fink.izbori.grpc.LogResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.LogResponse buildPartial() {
      rs.ac.fink.izbori.grpc.LogResponse result = new rs.ac.fink.izbori.grpc.LogResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.ac.fink.izbori.grpc.LogResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.entryAtIndex_ = entryAtIndex_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastEntryIndex_ = lastEntryIndex_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.ac.fink.izbori.grpc.LogResponse) {
        return mergeFrom((rs.ac.fink.izbori.grpc.LogResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.ac.fink.izbori.grpc.LogResponse other) {
      if (other == rs.ac.fink.izbori.grpc.LogResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getEntryAtIndex() != 0L) {
        setEntryAtIndex(other.getEntryAtIndex());
      }
      if (other.getLastEntryIndex() != 0L) {
        setLastEntryIndex(other.getLastEntryIndex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              entryAtIndex_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              lastEntryIndex_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.izbori.LogStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.izbori.LogStatus status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.izbori.LogStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public rs.ac.fink.izbori.grpc.LogStatus getStatus() {
      rs.ac.fink.izbori.grpc.LogStatus result = rs.ac.fink.izbori.grpc.LogStatus.forNumber(status_);
      return result == null ? rs.ac.fink.izbori.grpc.LogStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.izbori.LogStatus status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(rs.ac.fink.izbori.grpc.LogStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.izbori.LogStatus status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private long entryAtIndex_ ;
    /**
     * <code>int64 entry_at_index = 2;</code>
     * @return The entryAtIndex.
     */
    @java.lang.Override
    public long getEntryAtIndex() {
      return entryAtIndex_;
    }
    /**
     * <code>int64 entry_at_index = 2;</code>
     * @param value The entryAtIndex to set.
     * @return This builder for chaining.
     */
    public Builder setEntryAtIndex(long value) {

      entryAtIndex_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 entry_at_index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryAtIndex() {
      bitField0_ = (bitField0_ & ~0x00000002);
      entryAtIndex_ = 0L;
      onChanged();
      return this;
    }

    private long lastEntryIndex_ ;
    /**
     * <code>int64 last_entry_index = 3;</code>
     * @return The lastEntryIndex.
     */
    @java.lang.Override
    public long getLastEntryIndex() {
      return lastEntryIndex_;
    }
    /**
     * <code>int64 last_entry_index = 3;</code>
     * @param value The lastEntryIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLastEntryIndex(long value) {

      lastEntryIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_entry_index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastEntryIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastEntryIndex_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:izbori.LogResponse)
  }

  // @@protoc_insertion_point(class_scope:izbori.LogResponse)
  private static final rs.ac.fink.izbori.grpc.LogResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.ac.fink.izbori.grpc.LogResponse();
  }

  public static rs.ac.fink.izbori.grpc.LogResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogResponse>
      PARSER = new com.google.protobuf.AbstractParser<LogResponse>() {
    @java.lang.Override
    public LogResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LogResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.ac.fink.izbori.grpc.LogResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

