// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

/**
 * Protobuf type {@code izbori.StatisticsResponse}
 */
public final class StatisticsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:izbori.StatisticsResponse)
    StatisticsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatisticsResponse.newBuilder() to construct.
  private StatisticsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatisticsResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatisticsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_StatisticsResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetResultsPerCandidate();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_StatisticsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.ac.fink.izbori.grpc.StatisticsResponse.class, rs.ac.fink.izbori.grpc.StatisticsResponse.Builder.class);
  }

  public static final int PERCENTAGE_REPORTED_FIELD_NUMBER = 1;
  private double percentageReported_ = 0D;
  /**
   * <code>double percentage_reported = 1;</code>
   * @return The percentageReported.
   */
  @java.lang.Override
  public double getPercentageReported() {
    return percentageReported_;
  }

  public static final int TURNOUT_PERCENTAGE_FIELD_NUMBER = 2;
  private double turnoutPercentage_ = 0D;
  /**
   * <code>double turnout_percentage = 2;</code>
   * @return The turnoutPercentage.
   */
  @java.lang.Override
  public double getTurnoutPercentage() {
    return turnoutPercentage_;
  }

  public static final int RESULTS_PER_CANDIDATE_FIELD_NUMBER = 3;
  private static final class ResultsPerCandidateDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_StatisticsResponse_ResultsPerCandidateEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> resultsPerCandidate_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetResultsPerCandidate() {
    if (resultsPerCandidate_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ResultsPerCandidateDefaultEntryHolder.defaultEntry);
    }
    return resultsPerCandidate_;
  }
  public int getResultsPerCandidateCount() {
    return internalGetResultsPerCandidate().getMap().size();
  }
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  @java.lang.Override
  public boolean containsResultsPerCandidate(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetResultsPerCandidate().getMap().containsKey(key);
  }
  /**
   * Use {@link #getResultsPerCandidateMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer> getResultsPerCandidate() {
    return getResultsPerCandidateMap();
  }
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Integer> getResultsPerCandidateMap() {
    return internalGetResultsPerCandidate().getMap();
  }
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  @java.lang.Override
  public int getResultsPerCandidateOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetResultsPerCandidate().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  @java.lang.Override
  public int getResultsPerCandidateOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetResultsPerCandidate().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int STATIONS_NEEDING_RETRY_FIELD_NUMBER = 4;
  private int stationsNeedingRetry_ = 0;
  /**
   * <code>int32 stations_needing_retry = 4;</code>
   * @return The stationsNeedingRetry.
   */
  @java.lang.Override
  public int getStationsNeedingRetry() {
    return stationsNeedingRetry_;
  }

  public static final int TOTAL_STATIONS_FIELD_NUMBER = 5;
  private int totalStations_ = 0;
  /**
   * <code>int32 total_stations = 5;</code>
   * @return The totalStations.
   */
  @java.lang.Override
  public int getTotalStations() {
    return totalStations_;
  }

  public static final int VERIFIED_STATIONS_FIELD_NUMBER = 6;
  private int verifiedStations_ = 0;
  /**
   * <code>int32 verified_stations = 6;</code>
   * @return The verifiedStations.
   */
  @java.lang.Override
  public int getVerifiedStations() {
    return verifiedStations_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(percentageReported_) != 0) {
      output.writeDouble(1, percentageReported_);
    }
    if (java.lang.Double.doubleToRawLongBits(turnoutPercentage_) != 0) {
      output.writeDouble(2, turnoutPercentage_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetResultsPerCandidate(),
        ResultsPerCandidateDefaultEntryHolder.defaultEntry,
        3);
    if (stationsNeedingRetry_ != 0) {
      output.writeInt32(4, stationsNeedingRetry_);
    }
    if (totalStations_ != 0) {
      output.writeInt32(5, totalStations_);
    }
    if (verifiedStations_ != 0) {
      output.writeInt32(6, verifiedStations_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(percentageReported_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, percentageReported_);
    }
    if (java.lang.Double.doubleToRawLongBits(turnoutPercentage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, turnoutPercentage_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetResultsPerCandidate().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      resultsPerCandidate__ = ResultsPerCandidateDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, resultsPerCandidate__);
    }
    if (stationsNeedingRetry_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, stationsNeedingRetry_);
    }
    if (totalStations_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, totalStations_);
    }
    if (verifiedStations_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, verifiedStations_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.ac.fink.izbori.grpc.StatisticsResponse)) {
      return super.equals(obj);
    }
    rs.ac.fink.izbori.grpc.StatisticsResponse other = (rs.ac.fink.izbori.grpc.StatisticsResponse) obj;

    if (java.lang.Double.doubleToLongBits(getPercentageReported())
        != java.lang.Double.doubleToLongBits(
            other.getPercentageReported())) return false;
    if (java.lang.Double.doubleToLongBits(getTurnoutPercentage())
        != java.lang.Double.doubleToLongBits(
            other.getTurnoutPercentage())) return false;
    if (!internalGetResultsPerCandidate().equals(
        other.internalGetResultsPerCandidate())) return false;
    if (getStationsNeedingRetry()
        != other.getStationsNeedingRetry()) return false;
    if (getTotalStations()
        != other.getTotalStations()) return false;
    if (getVerifiedStations()
        != other.getVerifiedStations()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERCENTAGE_REPORTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPercentageReported()));
    hash = (37 * hash) + TURNOUT_PERCENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTurnoutPercentage()));
    if (!internalGetResultsPerCandidate().getMap().isEmpty()) {
      hash = (37 * hash) + RESULTS_PER_CANDIDATE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetResultsPerCandidate().hashCode();
    }
    hash = (37 * hash) + STATIONS_NEEDING_RETRY_FIELD_NUMBER;
    hash = (53 * hash) + getStationsNeedingRetry();
    hash = (37 * hash) + TOTAL_STATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalStations();
    hash = (37 * hash) + VERIFIED_STATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getVerifiedStations();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.StatisticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.ac.fink.izbori.grpc.StatisticsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code izbori.StatisticsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:izbori.StatisticsResponse)
      rs.ac.fink.izbori.grpc.StatisticsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_StatisticsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetResultsPerCandidate();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableResultsPerCandidate();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_StatisticsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.ac.fink.izbori.grpc.StatisticsResponse.class, rs.ac.fink.izbori.grpc.StatisticsResponse.Builder.class);
    }

    // Construct using rs.ac.fink.izbori.grpc.StatisticsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      percentageReported_ = 0D;
      turnoutPercentage_ = 0D;
      internalGetMutableResultsPerCandidate().clear();
      stationsNeedingRetry_ = 0;
      totalStations_ = 0;
      verifiedStations_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_StatisticsResponse_descriptor;
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.StatisticsResponse getDefaultInstanceForType() {
      return rs.ac.fink.izbori.grpc.StatisticsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.StatisticsResponse build() {
      rs.ac.fink.izbori.grpc.StatisticsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.StatisticsResponse buildPartial() {
      rs.ac.fink.izbori.grpc.StatisticsResponse result = new rs.ac.fink.izbori.grpc.StatisticsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.ac.fink.izbori.grpc.StatisticsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.percentageReported_ = percentageReported_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.turnoutPercentage_ = turnoutPercentage_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.resultsPerCandidate_ = internalGetResultsPerCandidate();
        result.resultsPerCandidate_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.stationsNeedingRetry_ = stationsNeedingRetry_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.totalStations_ = totalStations_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.verifiedStations_ = verifiedStations_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.ac.fink.izbori.grpc.StatisticsResponse) {
        return mergeFrom((rs.ac.fink.izbori.grpc.StatisticsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.ac.fink.izbori.grpc.StatisticsResponse other) {
      if (other == rs.ac.fink.izbori.grpc.StatisticsResponse.getDefaultInstance()) return this;
      if (other.getPercentageReported() != 0D) {
        setPercentageReported(other.getPercentageReported());
      }
      if (other.getTurnoutPercentage() != 0D) {
        setTurnoutPercentage(other.getTurnoutPercentage());
      }
      internalGetMutableResultsPerCandidate().mergeFrom(
          other.internalGetResultsPerCandidate());
      bitField0_ |= 0x00000004;
      if (other.getStationsNeedingRetry() != 0) {
        setStationsNeedingRetry(other.getStationsNeedingRetry());
      }
      if (other.getTotalStations() != 0) {
        setTotalStations(other.getTotalStations());
      }
      if (other.getVerifiedStations() != 0) {
        setVerifiedStations(other.getVerifiedStations());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              percentageReported_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              turnoutPercentage_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              resultsPerCandidate__ = input.readMessage(
                  ResultsPerCandidateDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableResultsPerCandidate().getMutableMap().put(
                  resultsPerCandidate__.getKey(), resultsPerCandidate__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              stationsNeedingRetry_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              totalStations_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              verifiedStations_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double percentageReported_ ;
    /**
     * <code>double percentage_reported = 1;</code>
     * @return The percentageReported.
     */
    @java.lang.Override
    public double getPercentageReported() {
      return percentageReported_;
    }
    /**
     * <code>double percentage_reported = 1;</code>
     * @param value The percentageReported to set.
     * @return This builder for chaining.
     */
    public Builder setPercentageReported(double value) {

      percentageReported_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double percentage_reported = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPercentageReported() {
      bitField0_ = (bitField0_ & ~0x00000001);
      percentageReported_ = 0D;
      onChanged();
      return this;
    }

    private double turnoutPercentage_ ;
    /**
     * <code>double turnout_percentage = 2;</code>
     * @return The turnoutPercentage.
     */
    @java.lang.Override
    public double getTurnoutPercentage() {
      return turnoutPercentage_;
    }
    /**
     * <code>double turnout_percentage = 2;</code>
     * @param value The turnoutPercentage to set.
     * @return This builder for chaining.
     */
    public Builder setTurnoutPercentage(double value) {

      turnoutPercentage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double turnout_percentage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTurnoutPercentage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      turnoutPercentage_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> resultsPerCandidate_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
        internalGetResultsPerCandidate() {
      if (resultsPerCandidate_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResultsPerCandidateDefaultEntryHolder.defaultEntry);
      }
      return resultsPerCandidate_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
        internalGetMutableResultsPerCandidate() {
      if (resultsPerCandidate_ == null) {
        resultsPerCandidate_ = com.google.protobuf.MapField.newMapField(
            ResultsPerCandidateDefaultEntryHolder.defaultEntry);
      }
      if (!resultsPerCandidate_.isMutable()) {
        resultsPerCandidate_ = resultsPerCandidate_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return resultsPerCandidate_;
    }
    public int getResultsPerCandidateCount() {
      return internalGetResultsPerCandidate().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
     */
    @java.lang.Override
    public boolean containsResultsPerCandidate(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetResultsPerCandidate().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResultsPerCandidateMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getResultsPerCandidate() {
      return getResultsPerCandidateMap();
    }
    /**
     * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Integer> getResultsPerCandidateMap() {
      return internalGetResultsPerCandidate().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
     */
    @java.lang.Override
    public int getResultsPerCandidateOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetResultsPerCandidate().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
     */
    @java.lang.Override
    public int getResultsPerCandidateOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetResultsPerCandidate().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearResultsPerCandidate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableResultsPerCandidate().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
     */
    public Builder removeResultsPerCandidate(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableResultsPerCandidate().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
        getMutableResultsPerCandidate() {
      bitField0_ |= 0x00000004;
      return internalGetMutableResultsPerCandidate().getMutableMap();
    }
    /**
     * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
     */
    public Builder putResultsPerCandidate(
        java.lang.String key,
        int value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableResultsPerCandidate().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
     */
    public Builder putAllResultsPerCandidate(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      internalGetMutableResultsPerCandidate().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private int stationsNeedingRetry_ ;
    /**
     * <code>int32 stations_needing_retry = 4;</code>
     * @return The stationsNeedingRetry.
     */
    @java.lang.Override
    public int getStationsNeedingRetry() {
      return stationsNeedingRetry_;
    }
    /**
     * <code>int32 stations_needing_retry = 4;</code>
     * @param value The stationsNeedingRetry to set.
     * @return This builder for chaining.
     */
    public Builder setStationsNeedingRetry(int value) {

      stationsNeedingRetry_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 stations_needing_retry = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStationsNeedingRetry() {
      bitField0_ = (bitField0_ & ~0x00000008);
      stationsNeedingRetry_ = 0;
      onChanged();
      return this;
    }

    private int totalStations_ ;
    /**
     * <code>int32 total_stations = 5;</code>
     * @return The totalStations.
     */
    @java.lang.Override
    public int getTotalStations() {
      return totalStations_;
    }
    /**
     * <code>int32 total_stations = 5;</code>
     * @param value The totalStations to set.
     * @return This builder for chaining.
     */
    public Builder setTotalStations(int value) {

      totalStations_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_stations = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalStations() {
      bitField0_ = (bitField0_ & ~0x00000010);
      totalStations_ = 0;
      onChanged();
      return this;
    }

    private int verifiedStations_ ;
    /**
     * <code>int32 verified_stations = 6;</code>
     * @return The verifiedStations.
     */
    @java.lang.Override
    public int getVerifiedStations() {
      return verifiedStations_;
    }
    /**
     * <code>int32 verified_stations = 6;</code>
     * @param value The verifiedStations to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedStations(int value) {

      verifiedStations_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 verified_stations = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerifiedStations() {
      bitField0_ = (bitField0_ & ~0x00000020);
      verifiedStations_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:izbori.StatisticsResponse)
  }

  // @@protoc_insertion_point(class_scope:izbori.StatisticsResponse)
  private static final rs.ac.fink.izbori.grpc.StatisticsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.ac.fink.izbori.grpc.StatisticsResponse();
  }

  public static rs.ac.fink.izbori.grpc.StatisticsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatisticsResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatisticsResponse>() {
    @java.lang.Override
    public StatisticsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StatisticsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatisticsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.ac.fink.izbori.grpc.StatisticsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

