// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public interface StatisticsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:izbori.StatisticsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double percentage_reported = 1;</code>
   * @return The percentageReported.
   */
  double getPercentageReported();

  /**
   * <code>double turnout_percentage = 2;</code>
   * @return The turnoutPercentage.
   */
  double getTurnoutPercentage();

  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  int getResultsPerCandidateCount();
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  boolean containsResultsPerCandidate(
      java.lang.String key);
  /**
   * Use {@link #getResultsPerCandidateMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getResultsPerCandidate();
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getResultsPerCandidateMap();
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  int getResultsPerCandidateOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; results_per_candidate = 3;</code>
   */
  int getResultsPerCandidateOrThrow(
      java.lang.String key);

  /**
   * <code>int32 stations_needing_retry = 4;</code>
   * @return The stationsNeedingRetry.
   */
  int getStationsNeedingRetry();

  /**
   * <code>int32 total_stations = 5;</code>
   * @return The totalStations.
   */
  int getTotalStations();

  /**
   * <code>int32 verified_stations = 6;</code>
   * @return The verifiedStations.
   */
  int getVerifiedStations();
}
