// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

/**
 * Protobuf type {@code izbori.VoteRequest}
 */
public final class VoteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:izbori.VoteRequest)
    VoteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VoteRequest.newBuilder() to construct.
  private VoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VoteRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VoteRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_VoteRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetVotesPerCandidate();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_VoteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            rs.ac.fink.izbori.grpc.VoteRequest.class, rs.ac.fink.izbori.grpc.VoteRequest.Builder.class);
  }

  public static final int CONTROLLER_ID_FIELD_NUMBER = 1;
  private int controllerId_ = 0;
  /**
   * <code>int32 controller_id = 1;</code>
   * @return The controllerId.
   */
  @java.lang.Override
  public int getControllerId() {
    return controllerId_;
  }

  public static final int STATION_ID_FIELD_NUMBER = 2;
  private int stationId_ = 0;
  /**
   * <code>int32 station_id = 2;</code>
   * @return The stationId.
   */
  @java.lang.Override
  public int getStationId() {
    return stationId_;
  }

  public static final int TOTAL_VOTED_FIELD_NUMBER = 3;
  private int totalVoted_ = 0;
  /**
   * <code>int32 total_voted = 3;</code>
   * @return The totalVoted.
   */
  @java.lang.Override
  public int getTotalVoted() {
    return totalVoted_;
  }

  public static final int INVALID_VOTES_FIELD_NUMBER = 4;
  private int invalidVotes_ = 0;
  /**
   * <code>int32 invalid_votes = 4;</code>
   * @return The invalidVotes.
   */
  @java.lang.Override
  public int getInvalidVotes() {
    return invalidVotes_;
  }

  public static final int VOTES_PER_CANDIDATE_FIELD_NUMBER = 5;
  private static final class VotesPerCandidateDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_VoteRequest_VotesPerCandidateEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> votesPerCandidate_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetVotesPerCandidate() {
    if (votesPerCandidate_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          VotesPerCandidateDefaultEntryHolder.defaultEntry);
    }
    return votesPerCandidate_;
  }
  public int getVotesPerCandidateCount() {
    return internalGetVotesPerCandidate().getMap().size();
  }
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  @java.lang.Override
  public boolean containsVotesPerCandidate(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetVotesPerCandidate().getMap().containsKey(key);
  }
  /**
   * Use {@link #getVotesPerCandidateMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer> getVotesPerCandidate() {
    return getVotesPerCandidateMap();
  }
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Integer> getVotesPerCandidateMap() {
    return internalGetVotesPerCandidate().getMap();
  }
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  @java.lang.Override
  public int getVotesPerCandidateOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetVotesPerCandidate().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  @java.lang.Override
  public int getVotesPerCandidateOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetVotesPerCandidate().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (controllerId_ != 0) {
      output.writeInt32(1, controllerId_);
    }
    if (stationId_ != 0) {
      output.writeInt32(2, stationId_);
    }
    if (totalVoted_ != 0) {
      output.writeInt32(3, totalVoted_);
    }
    if (invalidVotes_ != 0) {
      output.writeInt32(4, invalidVotes_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetVotesPerCandidate(),
        VotesPerCandidateDefaultEntryHolder.defaultEntry,
        5);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (controllerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, controllerId_);
    }
    if (stationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, stationId_);
    }
    if (totalVoted_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalVoted_);
    }
    if (invalidVotes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, invalidVotes_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetVotesPerCandidate().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      votesPerCandidate__ = VotesPerCandidateDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, votesPerCandidate__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof rs.ac.fink.izbori.grpc.VoteRequest)) {
      return super.equals(obj);
    }
    rs.ac.fink.izbori.grpc.VoteRequest other = (rs.ac.fink.izbori.grpc.VoteRequest) obj;

    if (getControllerId()
        != other.getControllerId()) return false;
    if (getStationId()
        != other.getStationId()) return false;
    if (getTotalVoted()
        != other.getTotalVoted()) return false;
    if (getInvalidVotes()
        != other.getInvalidVotes()) return false;
    if (!internalGetVotesPerCandidate().equals(
        other.internalGetVotesPerCandidate())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTROLLER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getControllerId();
    hash = (37 * hash) + STATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStationId();
    hash = (37 * hash) + TOTAL_VOTED_FIELD_NUMBER;
    hash = (53 * hash) + getTotalVoted();
    hash = (37 * hash) + INVALID_VOTES_FIELD_NUMBER;
    hash = (53 * hash) + getInvalidVotes();
    if (!internalGetVotesPerCandidate().getMap().isEmpty()) {
      hash = (37 * hash) + VOTES_PER_CANDIDATE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetVotesPerCandidate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static rs.ac.fink.izbori.grpc.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(rs.ac.fink.izbori.grpc.VoteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code izbori.VoteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:izbori.VoteRequest)
      rs.ac.fink.izbori.grpc.VoteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_VoteRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetVotesPerCandidate();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableVotesPerCandidate();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rs.ac.fink.izbori.grpc.VoteRequest.class, rs.ac.fink.izbori.grpc.VoteRequest.Builder.class);
    }

    // Construct using rs.ac.fink.izbori.grpc.VoteRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      controllerId_ = 0;
      stationId_ = 0;
      totalVoted_ = 0;
      invalidVotes_ = 0;
      internalGetMutableVotesPerCandidate().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return rs.ac.fink.izbori.grpc.Izbori.internal_static_izbori_VoteRequest_descriptor;
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.VoteRequest getDefaultInstanceForType() {
      return rs.ac.fink.izbori.grpc.VoteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.VoteRequest build() {
      rs.ac.fink.izbori.grpc.VoteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public rs.ac.fink.izbori.grpc.VoteRequest buildPartial() {
      rs.ac.fink.izbori.grpc.VoteRequest result = new rs.ac.fink.izbori.grpc.VoteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(rs.ac.fink.izbori.grpc.VoteRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.controllerId_ = controllerId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stationId_ = stationId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalVoted_ = totalVoted_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.invalidVotes_ = invalidVotes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.votesPerCandidate_ = internalGetVotesPerCandidate();
        result.votesPerCandidate_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof rs.ac.fink.izbori.grpc.VoteRequest) {
        return mergeFrom((rs.ac.fink.izbori.grpc.VoteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(rs.ac.fink.izbori.grpc.VoteRequest other) {
      if (other == rs.ac.fink.izbori.grpc.VoteRequest.getDefaultInstance()) return this;
      if (other.getControllerId() != 0) {
        setControllerId(other.getControllerId());
      }
      if (other.getStationId() != 0) {
        setStationId(other.getStationId());
      }
      if (other.getTotalVoted() != 0) {
        setTotalVoted(other.getTotalVoted());
      }
      if (other.getInvalidVotes() != 0) {
        setInvalidVotes(other.getInvalidVotes());
      }
      internalGetMutableVotesPerCandidate().mergeFrom(
          other.internalGetVotesPerCandidate());
      bitField0_ |= 0x00000010;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              controllerId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              stationId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              totalVoted_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              invalidVotes_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              votesPerCandidate__ = input.readMessage(
                  VotesPerCandidateDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableVotesPerCandidate().getMutableMap().put(
                  votesPerCandidate__.getKey(), votesPerCandidate__.getValue());
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int controllerId_ ;
    /**
     * <code>int32 controller_id = 1;</code>
     * @return The controllerId.
     */
    @java.lang.Override
    public int getControllerId() {
      return controllerId_;
    }
    /**
     * <code>int32 controller_id = 1;</code>
     * @param value The controllerId to set.
     * @return This builder for chaining.
     */
    public Builder setControllerId(int value) {

      controllerId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 controller_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearControllerId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      controllerId_ = 0;
      onChanged();
      return this;
    }

    private int stationId_ ;
    /**
     * <code>int32 station_id = 2;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public int getStationId() {
      return stationId_;
    }
    /**
     * <code>int32 station_id = 2;</code>
     * @param value The stationId to set.
     * @return This builder for chaining.
     */
    public Builder setStationId(int value) {

      stationId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 station_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStationId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      stationId_ = 0;
      onChanged();
      return this;
    }

    private int totalVoted_ ;
    /**
     * <code>int32 total_voted = 3;</code>
     * @return The totalVoted.
     */
    @java.lang.Override
    public int getTotalVoted() {
      return totalVoted_;
    }
    /**
     * <code>int32 total_voted = 3;</code>
     * @param value The totalVoted to set.
     * @return This builder for chaining.
     */
    public Builder setTotalVoted(int value) {

      totalVoted_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_voted = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalVoted() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalVoted_ = 0;
      onChanged();
      return this;
    }

    private int invalidVotes_ ;
    /**
     * <code>int32 invalid_votes = 4;</code>
     * @return The invalidVotes.
     */
    @java.lang.Override
    public int getInvalidVotes() {
      return invalidVotes_;
    }
    /**
     * <code>int32 invalid_votes = 4;</code>
     * @param value The invalidVotes to set.
     * @return This builder for chaining.
     */
    public Builder setInvalidVotes(int value) {

      invalidVotes_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 invalid_votes = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvalidVotes() {
      bitField0_ = (bitField0_ & ~0x00000008);
      invalidVotes_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> votesPerCandidate_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
        internalGetVotesPerCandidate() {
      if (votesPerCandidate_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VotesPerCandidateDefaultEntryHolder.defaultEntry);
      }
      return votesPerCandidate_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
        internalGetMutableVotesPerCandidate() {
      if (votesPerCandidate_ == null) {
        votesPerCandidate_ = com.google.protobuf.MapField.newMapField(
            VotesPerCandidateDefaultEntryHolder.defaultEntry);
      }
      if (!votesPerCandidate_.isMutable()) {
        votesPerCandidate_ = votesPerCandidate_.copy();
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return votesPerCandidate_;
    }
    public int getVotesPerCandidateCount() {
      return internalGetVotesPerCandidate().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
     */
    @java.lang.Override
    public boolean containsVotesPerCandidate(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetVotesPerCandidate().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVotesPerCandidateMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getVotesPerCandidate() {
      return getVotesPerCandidateMap();
    }
    /**
     * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Integer> getVotesPerCandidateMap() {
      return internalGetVotesPerCandidate().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
     */
    @java.lang.Override
    public int getVotesPerCandidateOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetVotesPerCandidate().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
     */
    @java.lang.Override
    public int getVotesPerCandidateOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetVotesPerCandidate().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearVotesPerCandidate() {
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableVotesPerCandidate().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
     */
    public Builder removeVotesPerCandidate(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableVotesPerCandidate().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
        getMutableVotesPerCandidate() {
      bitField0_ |= 0x00000010;
      return internalGetMutableVotesPerCandidate().getMutableMap();
    }
    /**
     * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
     */
    public Builder putVotesPerCandidate(
        java.lang.String key,
        int value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableVotesPerCandidate().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
     */
    public Builder putAllVotesPerCandidate(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      internalGetMutableVotesPerCandidate().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000010;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:izbori.VoteRequest)
  }

  // @@protoc_insertion_point(class_scope:izbori.VoteRequest)
  private static final rs.ac.fink.izbori.grpc.VoteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new rs.ac.fink.izbori.grpc.VoteRequest();
  }

  public static rs.ac.fink.izbori.grpc.VoteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoteRequest>
      PARSER = new com.google.protobuf.AbstractParser<VoteRequest>() {
    @java.lang.Override
    public VoteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VoteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public rs.ac.fink.izbori.grpc.VoteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

