// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public interface VoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:izbori.VoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.izbori.VoteStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.izbori.VoteStatus status = 1;</code>
   * @return The status.
   */
  rs.ac.fink.izbori.grpc.VoteStatus getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool verified = 3;</code>
   * @return The verified.
   */
  boolean getVerified();
}
