// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

public interface VoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:izbori.VoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 controller_id = 1;</code>
   * @return The controllerId.
   */
  int getControllerId();

  /**
   * <code>int32 station_id = 2;</code>
   * @return The stationId.
   */
  int getStationId();

  /**
   * <code>int32 total_voted = 3;</code>
   * @return The totalVoted.
   */
  int getTotalVoted();

  /**
   * <code>int32 invalid_votes = 4;</code>
   * @return The invalidVotes.
   */
  int getInvalidVotes();

  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  int getVotesPerCandidateCount();
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  boolean containsVotesPerCandidate(
      java.lang.String key);
  /**
   * Use {@link #getVotesPerCandidateMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getVotesPerCandidate();
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getVotesPerCandidateMap();
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  int getVotesPerCandidateOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; votes_per_candidate = 5;</code>
   */
  int getVotesPerCandidateOrThrow(
      java.lang.String key);
}
