// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: izbori.proto

package rs.ac.fink.izbori.grpc;

/**
 * Protobuf enum {@code izbori.VoteStatus}
 */
public enum VoteStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OK = 0;</code>
   */
  OK(0),
  /**
   * <code>INVALID_SUM = 1;</code>
   */
  INVALID_SUM(1),
  /**
   * <code>NOT_LEADER = 2;</code>
   */
  NOT_LEADER(2),
  /**
   * <code>STATION_BLOCKED = 3;</code>
   */
  STATION_BLOCKED(3),
  /**
   * <code>VERIFICATION_FAILED = 4;</code>
   */
  VERIFICATION_FAILED(4),
  /**
   * <code>STATION_VERIFIED = 5;</code>
   */
  STATION_VERIFIED(5),
  /**
   * <code>NEEDS_RETRY = 6;</code>
   */
  NEEDS_RETRY(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OK = 0;</code>
   */
  public static final int OK_VALUE = 0;
  /**
   * <code>INVALID_SUM = 1;</code>
   */
  public static final int INVALID_SUM_VALUE = 1;
  /**
   * <code>NOT_LEADER = 2;</code>
   */
  public static final int NOT_LEADER_VALUE = 2;
  /**
   * <code>STATION_BLOCKED = 3;</code>
   */
  public static final int STATION_BLOCKED_VALUE = 3;
  /**
   * <code>VERIFICATION_FAILED = 4;</code>
   */
  public static final int VERIFICATION_FAILED_VALUE = 4;
  /**
   * <code>STATION_VERIFIED = 5;</code>
   */
  public static final int STATION_VERIFIED_VALUE = 5;
  /**
   * <code>NEEDS_RETRY = 6;</code>
   */
  public static final int NEEDS_RETRY_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VoteStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VoteStatus forNumber(int value) {
    switch (value) {
      case 0: return OK;
      case 1: return INVALID_SUM;
      case 2: return NOT_LEADER;
      case 3: return STATION_BLOCKED;
      case 4: return VERIFICATION_FAILED;
      case 5: return STATION_VERIFIED;
      case 6: return NEEDS_RETRY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VoteStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VoteStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VoteStatus>() {
          public VoteStatus findValueByNumber(int number) {
            return VoteStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return rs.ac.fink.izbori.grpc.Izbori.getDescriptor().getEnumTypes().get(0);
  }

  private static final VoteStatus[] VALUES = values();

  public static VoteStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VoteStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:izbori.VoteStatus)
}

